spring:
  application:
    name: auth-service
  threads:
    virtual:
      enabled: true
  mongodb:
    uri: ${MONGO_URI:mongodb://admin:password@localhost:27017/auth_db?authSource=admin}

server:
  port: 8100
