spring:
  application:
    name: auth-service
  threads:
    virtual:
      enabled: true
  mongodb:
    uri: ${MONGO_URI:mongodb://admin:password@localhost:27017/auth_db?authSource=admin}
  security:
    oauth2:
      resourceserver:
        jwt:
          authorities-claim-name: permissions
          authority-prefix: ""

server:
  port: 8100

app:
  jwt:
    private-key: classpath:keys/private.pem
    public-key: classpath:keys/public.pem
    token-ttl: 15m
