spring:
  application:
    name: user-service
  threads:
    virtual:
      enabled: true
  mongodb:
    uri: ${MONGO_URI:mongodb://admin:password@localhost:27017/user_db?authSource=admin}
  http:
    clients:
      connect-timeout: 2s
      read-timeout: 5s
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:http://localhost:8100/.well-known/jwks.json}
          authorities-claim-name: permissions
          authority-prefix: ""

server:
  port: 8300

app:
  auth:
    base-url: ${AUTH_BASE_URL:http://localhost:8100}
    client-id: user-service
    client-secret: ${CLIENT_SECRET:user-service-secret}

management:
  otlp:
    metrics:
      export:
        enabled: false
